### ISSUE TITLE
Upgrade to Fable 1.0 and convert to template

### ISSUE THREAD

**Issue by alfonsogarciacaro** [fable-compiler/fable-getting-started#6]
@Pauan Could you please upgrade the project to Fable 1.0 (please check the [blog info](http://fable.io/blog/Introducing-1-0-beta.html) and ask me if you have questions) and convert it into a template? You can take the [simple Fable template](https://github.com/fable-compiler/Fable/tree/narumi/src/templates/simple) as reference. Or if you prefer, you can just add the files and I'll take care of the .nuspec and template.json configuration 👍 

> The [documentation for dotnet SDK templates](https://github.com/dotnet/templating/wiki/%22Runnable-Project%22-Templates) is still incomplete but there's [a tutorial here](http://pioneercode.com/post/how-to-create-a-dot-net-new-project-template-in-dot-net-core) if you need help.

**Comment by Pauan** [comment]
@alfonsogarciacaro Sure! I've been planning on doing it soon anyways, so I'll see if I can get it done in the next couple days or so.

Should the 1.0 version be on a new branch? Or maybe move the 0.7 version to a new branch? So that way people using 0.7 can still access the old instructions.

**Comment by forki** [comment]
A tag for the 0.7 version should be enough

**Comment by alfonsogarciacaro** [comment]
@Pauan Sorry, I forgot to mention that, for simplicity, it may be better to use simple Mocha bindings [as in the mocha sample](https://github.com/fable-compiler/Fable/blob/narumi/samples/node/mocha/index.fsx) instead of the nunit plugin (which was mainly created for sharing tests between .NET and JS). Also, please note that in order not to miss test files in the bundle, the last file of the test project should [make references to all the other test files](https://github.com/fable-compiler/Fable/blob/narumi/src/tests/Main/Main.fs).

**Comment by Pauan** [comment]
@forki You're right, a tag does sound better, thanks!

@alfonsogarciacaro Understood. It might not be a bad time for me to get `fable-unit-test` working.

**Comment by Pauan** [comment]
@alfonsogarciacaro I think this repo is now redundant:

If users want working code, the best way is to use one of the many Fable templates.

If users want step-by-step information on things like installing libraries, compiling, writing unit tests, etc. then that information should be in the fable.io docs.

So if you don't have any objections, I think I should deprecate this repo.
