### ISSUE TITLE
Webpack Express Error

### ISSUE THREAD

**Issue by aolney** [fable-compiler/fable-getting-started#7]
I've extended this for a server app. All the f# seems to compile fine, but webpack blows up during bundling with errors like this:

```
ERROR in ./~/express/lib/request.js
Module not found: Error: Can't resolve 'net' in '/z/aolney/repos/braintrust-server/node_modules/express/lib'
 @ ./~/express/lib/request.js 18:11-25
 @ ./~/express/lib/express.js
 @ ./~/express/index.js
 @ ./src/server.fs
 @ ./Server.fsproj
 @ multi (webpack)-dev-server/client?http://localhost:8080 babel-polyfill ./Server.fsproj
```

The offending line 18 is `var isIP = require('net').isIP;`, and `net` doesn't seem to be installed anywhere.

Is webpack configured incorrectly, or are the dependencies broken?

**Comment by Pauan** [comment]
The `net` module is a [built-in module in Node](https://nodejs.org/api/net.html)

I have no idea why Webpack would be breaking like that. Do you have your code in a repo somewhere, so I can take a look?

**Comment by aolney** [comment]
Thanks - working on a minimal reproduction, which might bring additional insight

**Comment by aolney** [comment]
Your tip was very helpful, seemed to be a webpack.config.js issue. Solved by adding
```
  externals: [
       /^(?!\.|\/).+/i,
  ],
  target: "node",
  node: {
    __dirname: false,
    __filename: false
  },
```
I think it's going to be another year before I master webpack

**Comment by forki** [comment]
Something wrong with our config?

Am 29.04.2017 19:28 schrieb "Andrew M Olney" <notifications@github.com>:

**Comment by alfonsogarciacaro** [comment]
I think the default Webpack target is `web` so it'll probably throw an error if you try to use node modules without changing the target. About `__dirname` it seems Webpack by default automatically replaces the macro instead of letting node do that later, that's not a very intuitive behavior to me.

**Comment by Pauan** [comment]
I think Webpack has to treat `__dirname` specially, because imagine this situation:

```
foo/bar/file1.js
foo/file2.js
```

Let's say both `file1.js` and `file2.js` are using `__dirname`

If you were running `file1.js` and `file2.js` directly in Node, then `__dirname` would be `foo/bar/` and `foo/` respectively.

But when using Webpack to bundle them into `out/bundle.js`, the `__dirname` will always be `out/`, because that's where the bundle is located. That breaks both `file1.js` and `file2.js`

**Comment by alfonsogarciacaro** [comment]
Ah, that makes sense. It just bite me in the fable-electron samples (I really wanted to get the `out` directory) and I guess @aolney had a similar issue :)

**Comment by Pauan** [comment]
Yeah, it's tricky. I think the default behavior of Webpack makes sense, but sometimes you don't want it.

**Comment by Pauan** [comment]
@forki I don't think there's anything wrong with our config, it's just that Webpack defaults to browser bundling, so if you want to make a Node bundle you have to specify `target: "node"`
